language: go
go:
  - 1.11.x
  - 1.12.x

before_install:
  - go get -t -v ./...
  - env

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - env

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - env

env:
  - GO111MODULE=on
