apiVersion: v1
kind: Template
metadata:
  name: uhc-auth-proxy-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: uhc-auth-proxy
    name: uhc-auth-proxy
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: uhc-auth-proxy
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: uhc-auth-proxy
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - uhc-auth-proxy
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - uhc-auth-proxy
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - env:
          - name: OAT
            valueFrom:
              secretKeyRef:
                key: offline_access_token
                name: uhc-auth-proxy-secret
          - name: CURRENT_ACCOUNT_URL
            value: ${OPENSHIFT_API_TARGET}
          - name: SERVER_PORT
            value: '8080'
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: CW_AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws_secret_access_key
                name: cloudwatch
          - name: CW_AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws_access_key_id
                name: cloudwatch
          - name: CW_AWS_REGION
            valueFrom:
              secretKeyRef:
                key: aws_region
                name: cloudwatch
          - name: CW_LOG_GROUP
            valueFrom:
              secretKeyRef:
                key: log_group_name
                name: cloudwatch
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: client_id
                name: uhc-auth-proxy-secret
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: client_secret
                name: uhc-auth-proxy-secret
          image: ${REGISTRY_IMG}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: uhc-auth-proxy
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 60
          resources:
            limits:
              cpu: ${CPU_LIMIT} 
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUESTS}
              memory: ${MEMORY_REQUESTS}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: cloudservices-buildfactory-pull-secret
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: uhc-auth-proxy
    name: uhc-auth-proxy
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: uhc-auth-proxy
    sessionAffinity: None
    type: ClusterIP
parameters:
- name: REGISTRY_IMG
  required: false
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest
- name: OPENSHIFT_API_TARGET
  value: https://api.openshift.com/api/accounts_mgmt/v1/current_account
- name: REPLICAS
  description: The number of replicas to use in the deployment
  value: '1'
- name: LOG_LEVEL
  required: true
  value: INFO
- description: cpu limit for service
  name: CPU_LIMIT
  value: 150m
- description: memory limit for service
  name: MEMORY_LIMIT
  value: 400Mi
- description: requested cpu for service
  name: CPU_REQUESTS
  value: 25m
- description: requested memory for service
  name: MEMORY_REQUESTS
  value: 200Mi
