apiVersion: v1
kind: Template
metadata:
  name: uhc-auth-proxy-template
parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: uhc-auth-proxy
    name: uhc-auth-proxy
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: uhc-auth-proxy
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: uhc-auth-proxy
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - uhc-auth-proxy
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - uhc-auth-proxy
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - env:
          - name: OAT
            valueFrom:
              secretKeyRef:
                key: offline_access_token
                name: uhc-auth-proxy-secret
          - name: SERVER_PORT
            value: '8080'
          image: ${REGISTRY_IMG}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: uhc-auth-proxy
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: cloudservices-buildfactory-pull-secret
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: uhc-auth-proxy
    name: uhc-auth-proxy
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: uhc-auth-proxy
    sessionAffinity: None
    type: ClusterIP
